const List<String> fieldDescription = [
  "Candidate's First Name",
  "Date of Birth",
  "Place of Birth",
  "Gender",
  "Mother Tongue",
  "Blood Group",
  "Religion",
  "Social Category",
  "Aadhar Card Number",
  "Aadhar Enrollment ID",
  "Last School Attended",
  "Last Class Attended",
  "Admission Sought for Class",
  "Father's First Name",
  "Father's Profession",
  "Father's Qualification",
  "Father's Home/Personal Contact",
  "Father's Email ID",
  "Mother's First Name",
  "Mother's Profession",
  "Mother's Qualification",
  "Mother's Home/Personal Contact",
  "Mother's Email ID",
  "Present Location",
  "Present State",
  "Present PIN Code",
  "Permanent Location",
  "Permanent State",
  "Permanent PIN Code",
  "I AGREE Checkbox",
];

List<String> motherTongueList = [
  "ASSAMESE",
  "BANGLA",
  "BODO",
  "DOGRI",
  "ENGLISH",
  "GUJARATI",
  "HINDI",
  "KANNADA",
  "KASHMIRI",
  "KHADIA",
  "KONKANI",
  "KURUKH",
  "MAITHILI",
  "MALAYALAM",
  "MANIPURI",
  "MARATHI",
  "MUNDARI",
  "NEPALI",
  "ODIA",
  "PUNJABI",
  "SADRI",
  "SANSKRIT",
  "SANTALI",
  "SINDHI",
  "TAMIL",
  "TELUGU",
  "URDU",
];

List<String> genderList = [
  "MALE",
  "FEMALE",
];

List<String> bloodGroupList = [
  "O+",
  "O-",
  "A+",
  "A-",
  "B+",
  "B-",
  "AB-",
  "AB+",
];

List<String> religionList = [
  "CHRISTIAN (ROMAN CATHOLIC)",
  "CHRISTIAN (NON CATHOLIC)",
  "BUDDHIST",
  "JEW",
  "HINDU",
  "SIKH",
  "ZOROASTRIAN",
  "JAIN",
  "NOT APPLICABLE",
  "ISLAM",
  "BAHAI",
  "KHASI",
  "MEITEI",
  "SARNAISM",
  "INDIGENOUS",
];

List<String> socialCategoryList = [
  "GENERAL",
  "SC",
  "ST",
  "OBC",
];

List<String> relationshipList = [
  "NONE",
  "BROTHER",
  "SISTER",
];

List<String> hasAadharCardList = [
  "YES",
  "NO",
];

List<String> classList = [
  "LKG",
  // "UKG",
  // "CLASS 1",
  // "CLASS 2",
  // "CLASS 3",
  // "CLASS 4",
  // "CLASS 5",
  // "CLASS 6",
  // "CLASS 7",
  // "CLASS 8",
  // "CLASS 9",
];

List<String> professionList = [
  "OTHERS",
  "CRPF",
  "RSP EMPLOYEE",
  "NSPCL EMPLOYEE",
  "ACCOUNTANT",
  "ACTOR",
  "ACTUARY",
  "ACUPUNCTURIST",
  "ADVOCATE",
  "AGRICULTURIST",
  "AGROLOGIST",
  "AIR TRAFFIC CONTROLLER",
  "AIRCRAFT PILOT",
  "ARCHITECT",
  "ARTIST",
  "ASSISTANT LIBRARIAN",
  "ASSISTANT PROFESSOR NIT",
  "ASSOCIATE PROFESSOR NIT",
  "PROFESSOR NIT",
  "ASTROLOGER",
  "ASTRONOMER",
  "ATTORNEY AT LAW",
  "AUDIOLOGIST",
  "AUDITOR",
  "BAKER",
  "BANK MANAGER",
  "BANKER",
  "BARBER",
  "BIOLOGIST",
  "BLACKSMITH",
  "BOTANIST",
  "BUSINESS",
  "CARPENTER",
  "CERTIFIED GENERAL ACCOUNTANT",
  "CERTIFIED HUMAN RESOURCES AND INDUSTRIAL RELATIONS COUNSELLOR",
  "CHARTERED APPRAISER",
  "CHEMIST",
  "CHOREOGRAPHER",
  "CONTRACTOR",
  "CRIMINOLOGIST",
  "DANCE TEACHER",
  "DENTAL HYGIENIST",
  "DENTAL TECHNICIAN",
  "DENTIST",
  "DENTUROLOGIST",
  "DESIGNER",
  "DHOBI",
  "DIETICIAN",
  "DOCTOR",
  "ECOLOGIST",
  "ECONOMIST",
  "ENGINEER",
  "FARMER",
  "FINANCE",
  "FIREFIGHTER",
  "FOREST ENGINEER",
  "FORESTER",
  "GARDENER",
  "GEOLOGIST",
  "GOLDSMITH",
  "GRAPHIC DESIGNER",
  "GUIDANCE COUNSELLOR",
  "HEARING-AID ACOUSTICIAN",
  "HUMAN RESOURCE",
  "INTERPRETER",
  "JUDGE",
  "LAND-SURVEYOR",
  "LAWYER",
  "LECTURER",
  "LIBRARIAN",
  "LIC AGENT",
  "LOCO PILOT",
  "MEDICAL LABORATORY SCIENTIST",
  "MEDICAL TECHNOLOGIST",
  "METEOROLOGIST",
  "MIDWIFERY",
  "MILITARY OFFICER",
  "MILKMAN",
  "MUSICIAN",
  "NOTARY",
  "NURSE",
  "NURSING ASSISTANT",
  "OCCUPATIONAL THERAPIST",
  "PAINTER",
  "PATHOLOGIST",
  "PEDIATRICIAN",
  "PHARMACIST",
  "PHARMACOLOGIST",
  "PHILOSOPHER",
  "PHOTOGRAPHER",
  "PHYSICAL THERAPIST",
  "PHYSICIAN",
  "PHYSIOTHERAPIST",
  "POLICE OFFICER",
  "POSTAL WORKER",
  "POSTMASTER",
  "PRINTER",
  "PROFESSIONAL TECHNOLOGIST",
  "PROFESSOR",
  "PROGRAMMER",
  "PSYCHOLOGIST",
  "REFREE",
  "RESEARCH SCHOLAR",
  "SALES MANAGER",
  "SCIENTIST",
  "SECRETARY",
  "SOCIAL WORKER",
  "STATION MASTER",
  "STATISTICIAN",
  "SURVEYORS",
  "SWEEPER",
  "TAILOR",
  "TEACHER",
  "TECHINICIAN",
  "URBANIST",
  "VENDOR",
  "VETERINARY DOCTOR",
  "VETERINARY SURGEONS",
  "VISUAL ARTIST",
  "WEB DESIGNER",
  "WEB DEVELOPER",
  "WRITER",
  "ZOOLOGIST",
];

List<String> qualificationList = [
  "OTHERS",
  "12 ARTS",
  "12 COMMERCE",
  "12 SCIENCE",
  "B.ARTS",
  "B.AYURVEDIC MEDICINE SURGERY",
  "B.COMMERCE",
  "B.E.",
  "B.ED",
  "B.FIRE ENGINEERING",
  "B.LAW",
  "B.OPTOMETRY",
  "B.PHARM",
  "B.PSYCHOLOGY",
  "B.SCIENCE",
  "B.TECH",
  "B.V.SC & A.H.",
  "BA.LLB",
  "BBM",
  "BCA",
  "BELOW MATRIC",
  "AMIE",
  "DIPLOMA",
  "PHD SCHOLAR",
  "FASHION DESIGN",
  "SURGERY",
  "GNIIT",
  "ICAI",
  "ICWA",
  "ITI",
  "LLB",
  "M.ARTS",
  "M.B.B.S",
  "M.CH",
  "M.COMMERCE",
  "M.PHIL",
  "M.SCIENCE",
  "M.TECH",
  "MATRICULATION",
  "MBA",
  "MCA",
  "PG IN MANAGEMENT",
  "PHD",
];
