// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD71A_OGuYvtb7fTKPOr3FgWZ7Gsb7K3b8',
    appId: '1:167009655082:web:dac8d439eb7204f8876653',
    messagingSenderId: '167009655082',
    projectId: 'stpaulsrkl-admission',
    authDomain: 'stpaulsrkl-admission.firebaseapp.com',
    storageBucket: 'stpaulsrkl-admission.appspot.com',
    measurementId: 'G-4N2VB0G6L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgKuBI8F2HuDq8PHOefR6W2gBNy_vIUA',
    appId: '1:167009655082:android:7aea82129f94e51d876653',
    messagingSenderId: '167009655082',
    projectId: 'stpaulsrkl-admission',
    storageBucket: 'stpaulsrkl-admission.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFRNqX_Tq4_uopt4Rj0fFgMjzT2wmfldU',
    appId: '1:167009655082:ios:5b46d778095e53e7876653',
    messagingSenderId: '167009655082',
    projectId: 'stpaulsrkl-admission',
    storageBucket: 'stpaulsrkl-admission.appspot.com',
    androidClientId: '167009655082-dbgmthmf7cbt7l0c870vn7fg6ok8vh7k.apps.googleusercontent.com',
    iosClientId: '167009655082-ts04pm5h847fl1n2p41thmjn65hgenb6.apps.googleusercontent.com',
    iosBundleId: 'in.i9studios.stpaulsrkl.admission',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFRNqX_Tq4_uopt4Rj0fFgMjzT2wmfldU',
    appId: '1:167009655082:ios:5b46d778095e53e7876653',
    messagingSenderId: '167009655082',
    projectId: 'stpaulsrkl-admission',
    storageBucket: 'stpaulsrkl-admission.appspot.com',
    androidClientId: '167009655082-dbgmthmf7cbt7l0c870vn7fg6ok8vh7k.apps.googleusercontent.com',
    iosClientId: '167009655082-ts04pm5h847fl1n2p41thmjn65hgenb6.apps.googleusercontent.com',
    iosBundleId: 'in.i9studios.stpaulsrkl.admission',
  );
}
